### ISSUE TITLE
redis를 이용해 캐싱하기

### ISSUE THREAD

**Issue by didrlgus** [didrlgus/springboot-shoppingmall#17]
# :memo: Redis 기본 개념
* In-memory 데이터 베이스
* 기존 관계형 데이터베이스(Oracle, MySQL) 보다 훨씬 빠른데 그 이유는 메모리 접근이 디스크 접근보다 빠르기 때문.
*  In-Memory 데이터베이스(ex. Memcached) 와의 가장 큰 차이점은 다양한 자료구조 를 지원 한다는 것
* redis 는 다양한 자료구조를 Key-Value 형태로 저장함
<img width="591" alt="캡처" src="https://user-images.githubusercontent.com/40568894/93711780-eccb6500-fb8b-11ea-8165-ca6c8fb78ca5.PNG">

# :wrench: Spring boot와 Redis 연동 (#18)
### Spring Data Redis
* Redis를 마치 JPA Repository를 이용하듯이 인터페이스를 제공하는 스프링 모듈
* CrudRepository를 지원하기 때문에 좀 더 직관적으로 사용 가능
* DB 연동을 위한 추상화 된 프로그래밍 지원
  * RedisRepository (JPA 처럼 redis 사용 가능)
  * redisTemplate

### Redis Java Client
**1. Lettuce**
* Netty (비동기 이벤트 기반 고성능 네트워크 프레임워크) 기반의 Redis Client, 비동기로 요청을 처리하기 때문에 고성능.

**2. Jedis**

> Lettuce가 Jedis 보다 성능이 뛰어남 ([참고](https://jojoldu.tistory.com/418))
> 그렇기 때문에 Redis Java Client로 Lettuce 선택

### Embedded redis
* local 환경에서 redis가 없더라도 embedded redis를 사용할 수 있도록 설정

# :wrench: Redis에 캐싱할 데이터
> 우선, 메인 화면을 띄울 데이터들만 캐싱

<img width="180" alt="캐시데이터0" src="https://user-images.githubusercontent.com/40568894/94996656-e6ec6f80-05e0-11eb-9cd0-938f78f19529.PNG">

---

### **1. 상품 카테고리 데이터**
<img width="348" alt="카테고리" src="https://user-images.githubusercontent.com/40568894/93729389-3dc87100-fbff-11ea-9782-e7ddccecbba9.PNG">

* 캐싱된 카테고리 데이터
  * string 자료구조
<img width="948" alt="캐시데이터3" src="https://user-images.githubusercontent.com/40568894/94996705-2f0b9200-05e1-11eb-98ad-f6b1456162b8.PNG">

---

### **2. Best Product 10개**
<img width="844" alt="인기" src="https://user-images.githubusercontent.com/40568894/93729390-3ef99e00-fbff-11ea-83b2-fd002c140982.PNG">

* 캐싱된 인기 상품 데이터
  * sorted-set 자료구조 (purchase_count를 score로 지정하여 sort)
    * sorted-set을 이용하면 최신 상품 데이터를 저장하고 있음을 보장 받을 수 있음
<img width="247" alt="인기1" src="https://user-images.githubusercontent.com/40568894/95430669-0be93580-0987-11eb-8347-d4722d1c7cdb.PNG">

<img width="946" alt="인기2" src="https://user-images.githubusercontent.com/40568894/95430674-0ee42600-0987-11eb-8ab8-91a44ae50ef1.PNG">

---

### **3. 최신 순 Product 8개**
<img width="832" alt="최신" src="https://user-images.githubusercontent.com/40568894/93729393-40c36180-fbff-11ea-86c9-bd518998af30.PNG">

* 캐싱된 최신 상품 데이터
  * sorted-set 자료구조 (created_date의 **timestamp**를 score로 지정하여 sort)
    * sorted-set을 이용하면 최신 상품 데이터를 저장하고 있음을 보장 받을 수 있음
<img width="220" alt="최신1" src="https://user-images.githubusercontent.com/40568894/95430251-751c7900-0986-11eb-963d-d7c737290ab8.PNG">

<img width="948" alt="최신2" src="https://user-images.githubusercontent.com/40568894/95430261-79e12d00-0986-11eb-8518-bd3fe1a2be34.PNG">

---

# 🔧 시스템 구성
<img width="638" alt="구조" src="https://user-images.githubusercontent.com/40568894/93733059-cdc1e700-fc0e-11ea-9535-287b2ba318a8.PNG">

### 👍 위 구조의 장점
1. 실제로 사용되는 데이터만 캐시할 수 있다.
2. 레디스의 장애가 어플리케이션에 치명적인 영향을 주지 않는다.

### 👎 위 구조의 단점
1. cache miss 상황이면 더 오랜 시간이 걸린다. (cache i/o 추가 발생)
2. 캐시가 최신 데이터를 가지고 있다는 것을 보장하지 못한다.

> 위에서 캐싱의 대상이 되는 데이터는 실시간으로 동기를 맞춰야 하는 성격의 데이터들은 아니다.
> 특정 시간 혹은 캐싱된 데이터에 TTL을 설정해 캐시를 업데이트 시켜주면 될 것이라 판단함

**Comment by joey-yoonsung** [comment]
캐시가 최신 데이터를 가지고 있다는 것을 보장하지 못한다.

- 보장하도록 만드려면 어떻게 해야할까요?

**Comment by didrlgus** [comment]
캐시가 최신 데이터를 가지도록 보장하려면
일단, 상품 카테고리 데이터 혹은 최신 상품 데이터 같은 경우에는 관리자에 의해 변화되는 데이터이고 사용자에 의해 변화하는 데이터는 아니니까, 상품 카테고리나 최신 상품이 추가 될 때마다 캐시를 업데이트 시켜주면 될 것 같다는 생각입니다.
반면, 인기 상품 데이터는 사용자가 해당 상품을 얼마나 구매했는냐에 따라 달라지는 데이터라 주문이 엄청 많다는 가정에서는 상품이 구입 될 때마다 매번 캐시를 업데이트 시키지는 못할 것 같습니다. 
다만, 인기 상품 데이터가 정말 실시간을 보장해야 되는 데이터는 아니라고 생각되기 때문에 일정 간격을 두고 캐시를 업데이트 시키는 식으로 가면 될 것 같다는 생각입니다.

**Comment by joey-yoonsung** [comment]
@didrlgus 넵. 그렇게 하시면 될것 같습니다.
일정간격을 두고 -> 배치라고 합니다. 배치 어플리케이션이 별도로 필요하겠네요.
배치를 어떤 도구를 써서 할 수 있을지 생각해보시겠어요?
그냥 지금 상태로 스프링 서버에 코드로 넣는것은 힘들거에요. 왜냐면 서버가 두대니까.. 동시에 두개가 돌겠죠?

스프링 환경에서 많이쓰는것은 다음과 같은 것들이 있습니다.
1. quartz
2. spring-cloud-batch
