### ISSUE TITLE
API 성능 테스트 결과

### ISSUE THREAD

**Issue by didrlgus** [didrlgus/springboot-shoppingmall#5]
# 초기 환경 세팅
<img width="452" alt="캡처1" src="https://user-images.githubusercontent.com/40568894/91185726-21810380-e729-11ea-823e-e7ac37fad20a.PNG">

* local
  * CPU i3, mem 8GB, ssd 256GB
* AWS EC2
  * vCPU 1, mem 1GB, ssd 30GB (프리티어 스펙)
* k6 API 테스팅 도구 사용
  * command: k6 run --vus 1000 --iterations 10000 --summary-export=export.json example.js
    * This command create 1000 concurrent sessions (virtual users), and would run this single requests 10 times for each virtual user, hence 10,000 iterations.
---
# 메인화면 조회 API
* **_Request Path_**
  * /

* **_수행 쿼리_**
  1. category 조회
  2. 베스트 상품 조회 (purchase_count desc, limit 10)
  3. 할인 여부 조회
  4. 최신 상품 조회 (created_date desc, limit 8)

* [k6 result matrix](https://k6.io/docs/using-k6/metrics)
  * vUser: Current number of active virtual users
  * iter: The aggregate number of times the VUs in the test have executed the JS script (the default function).

* **_API load test result_** 

|유저 수, 총 요청 수|평균 요청 처리 시간(ms)|초당 처리 요청 수 |성공 요청|실패 요청|
|----------|---------------:|------:|------:|------:|
|vUser: 10,    iter: 100|541.3152|6.3430/s|100|0|
|vUser:100, iter: 1000|3180.6745|22.8863/s|1000|0|
|vUser:1000, iter: 10000| 35190.7789|26.2413/s|9910|90

* **_요청 실패 시 발생 예외_**
<img width="949" alt="sql timeout error" src="https://user-images.githubusercontent.com/40568894/91188372-2f845380-e72c-11ea-96a7-c33a5b8de123.PNG">

> * connection pool을 50으로 설정 (default: 10)
>   <img width="216" alt="connection-pool" src="https://user-images.githubusercontent.com/40568894/91399988-e510ed00-e879-11ea-85c3-823f2287bafd.PNG">  

> * 수정 후 결과
>   <img width="949" alt="sql timeout error2" src="https://user-images.githubusercontent.com/40568894/91401620-cf9cc280-e87b-11ea-9a0b-d6e064ecb7e7.PNG">
> * 여전히 예외 발생
>   * connection pool을 150으로 설정
>   <img width="948" alt="error1" src="https://user-images.githubusercontent.com/40568894/91408587-0f18de00-e87f-11ea-821b-fc9eb9337e2b.PNG">
>     서버가 죽어버림...

# 문제점
  1. tps가 너무 낮다.
      - Local PC 에서 WAS로 쏠 수 있는 초당 request 수가 너무 적다.  
         (매번 떠있는 프로세스가 다르기 때문에 일관성 있게 테스트를 진행할 수가 없음)
  2. 동시 접속자 (vUser) 가 많아지면 memory 문제가 발생하면서 서버가 죽는다.
      - WAS, DB가 떠 있는 서버의 사양이 너무 낮다. (vCPU:1,mem:1)
      - 즉, DB connection 을 저장할 메모리 공간이 너무 적다.

**Comment by joey-yoonsung** [comment]
초당요청수가 26 이상으로 안올라가네요. 테스트라고 하기에 좀 적은 수치인데요. 최소 1000tps - 10000tps 까지는 테스트를 해야하는데요. 혹시 test client 가 여러대의 VM에서 돌게 하는 것을 고려해주실 수 있을까요?

**Comment by joey-yoonsung** [comment]
Connection is not available - 
1. Connection pool 을 늘리는 방법을 찾아보세요.
