### ISSUE TITLE
API 성능 테스트 에서 발생한 문제 해결을 위한 시도

### ISSUE THREAD

**Issue by didrlgus** [didrlgus/springboot-shoppingmall#6]
# :question: #5 API 성능 테스트 issue
1. 낮은 tps
2. Connection is not available, request timing out 30000ms 에러 발생 
3. max connection pool 증가 설정 시 메모리 부족으로 인한 서버 다운

# :point_up: 문제 해결을 위한 첫 번째 시도
### Test를 담당하는 Test client를 Local이 아닌  별도의 VM으로 생성
* Test를 담당하는 VM의 사양을 늘려가며 테스트 진행

<img width="476" alt="캡처" src="https://user-images.githubusercontent.com/40568894/91524486-557f4300-e93a-11ea-8818-0d50393e4529.PNG">

1. **vCpu 1, mem 1GB (프리티어 스펙)**
   초당 처리 요청 수 -> 27(tps)
2. **vCpu 8, mem 32GB**
   초당 처리 요청 수 -> 28(tps)

### :memo: 결과
* Test client를 별도의 VM으로 구축하고 서버의 사양을 늘려도 tps는 큰 변화 없음

# :v: 문제 해결을 위한 두 번째 시도
### 환경 세팅
* DB를 띄울 보다 높은 사양의 VM 구축
* WAS에 할당되는 memory, connection pool 개수를 변경해가면서 tps 측정
* JVM의 Heap영역 할당량을 점차 늘려가며 테스트 진행
  * default 최초 50m(-Xms), 최대 256(-Xmx)
  > **Heap Size 설정 Command**
  > $ Java -Xms256m -Xmx256m -jar [jar파일명]
  > **Heap Size 확인 Command**
  > $ java -XX:+PrintFlagsFinal -version | grep HeapSize  

<img width="491" alt="캡처1" src="https://user-images.githubusercontent.com/40568894/91628010-a5bbdb00-e9f6-11ea-8e96-aed184b2a67f.PNG">

* **Test Server, App Server, DB Server** 별도 분리
  * Test Server (vCPU:2, mem:8GB)
  * App Server (vCPU: 8, mem: 32GB)
  * DB Server (vCPU: 4, mem: 16GB) 

### JVM의 heap 할당량, connection pool 개수에 따른 성능 측정 결과
* vUser: 1000, iter: 10000 고정 (total 10000번의 request, [참고자료](https://k6.io/docs/using-k6/metrics))
> **heap size setting 해서 jar 실행하는 Command**
> $ java -jar -Xms4G -Xmx4G [jar 파일명] 

 ### :rocket: **_Test 1_**. Heap Size: Xms:256m, Xmx:256m

|DB 커넥션 개수|평균 요청 처리 시간(ms)|초당 처리 요청 수 |성공 요청|실패 요청|
|----------------:|---------------:|------:|------:|------:|
|  10|4064.8329|186.1573/s|10000|0|
|100|4274.7714|181.2829/s|10000|0|
|200|4274.7714|181.2829/s|10000|0|

 ### :rocket: **_Test 2_**. Heap Size: Xms:512m, Xmx:512m

|DB 커넥션 개수|평균 요청 처리 시간(ms)|초당 처리 요청 수 |성공 요청|실패 요청|
|----------------:|---------------:|------:|------:|------:|
|  10|3383.2243|216.6956/s|10000|0|
|100|3694.1383|202.5963/s|10000|0|
|200|4767.2096|166.2798/s|10000|0|

 ### :rocket: **_Test 3_**. Heap Size: Xms:1G, Xmx:1G

|DB 커넥션 개수|평균 요청 처리 시간(ms)|초당 처리 요청 수 |성공 요청|실패 요청|
|----------------:|---------------:|------:|------:|------:|
|  10|4134.4234|184.5289/s|10000|0|
|100|3455.0017|214.5464/s|10000|0|
|200|3498.0202|212.3586/s|10000|0|

 ### :rocket: **_Test 4_**. Heap Size: Xms:2G, Xmx:2G

|DB 커넥션 개수|평균 요청 처리 시간(ms)|초당 처리 요청 수 |성공 요청|실패 요청|
|----------------:|---------------:|------:|------:|------:|
|  10|3284.4063|221.6884/s|10000|0|
|100|4230.2421|181.9622/s|10000|0|
|200|4266.0610|181.8969/s|10000|0|

 ### :rocket: **_Test 5_**. Heap Size: Xms:4G, Xmx:4G

|DB 커넥션 개수|평균 요청 처리 시간(ms)|초당 처리 요청 수 |성공 요청|실패 요청|
|----------------:|---------------:|------:|------:|------:|
|  10|4078.0878|186.1689/s|10000|0|
|100|4322.5183|179.1167/s|10000|0|
|200|3494.2840|212.8465/s|10000|0|

### :memo: 결과
* tps가 20대에서 최대 200대로 높아짐
  * max: 221.6884/s (heap size:2GB, connection: 10), min: 166.2798/s (heap size:512MB, connection: 200)
  * WAS에 할당된 Heap Size, Connection Pool Size가 높다고 tps가 잘나오는 것은 아니었음
    * Heap Size가 커지고 connection pool size가 높으면 tps도 높아질 것이라 예상했는데 그렇지는 않았음.
* 모든 요청 테스트 성공 응답 (100%)

**Comment by joey-yoonsung** [comment]
client 인 스프링 앱에서 connection pool을 늘리더라도 연결을 받아주는 MySQL 서버에서 connection pool 이 적다면 효과가 없을 수 있습니다.
 
MySQL console 들어가셔서 아래 명령어로 max connection 을 바꾸면서 테스트해보시겠어요?(Test 5에서)

`SET GLOBAL max_connections = $whatyouwant;`

official doc 은 여기있습니다. https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_connections
* default 가 125 이어서 connection 늘리는 것에 비해서 tps 가 안높아졌을것 같아요. 
* 256, 512, 1024, 2048 까지 늘려보세요. (2000개 이상은 의미없음)

**Comment by joey-yoonsung** [comment]
테스트는 같은 옵션에 대해서 몇회 하시고 평균내시는걸까요? 1번만 수행하시면 input 지표와 output 지표가 inversion 된 경우가 나올 수 있습니다. 
저같으면 같은 옵션으로 여러차례 수행하고 그 결과들을 avg 내는 스크립트를 만들어서 테스트를 수행할 것 같아요.

예를들어서, vUser: 100, iter: 10000  로 하나의 옵션에 대해서 테스트한다면.
 1. Spring server 시작
 2. k6를 실행 -> 수행 끝날때까지 기다림. 결과 json 저장. 
 3. Spring server 서버 중지
 *  위 1,2,3 을 15초 간격을 두고 10번 수행.
 * 결과물인 10개의 json 결과물을 aggregation 해서 평균냄.
      * 이런거 짜기 좋은게 python script. json parsing이 쉽고, numpy,pandas 같은 라이브러리로 쉽게 평균내거나 추이 뽑을 수 있음.
      * 직접 짜기 어렵다면, elasticsearch 에 결과 json 모두 넣어놓고, elasticsearch + kibana 이용해서 average 구하는 방법도 있음.
