### ISSUE TITLE
질문드려요

### ISSUE THREAD

**Issue by shin-minkyung** [didrlgus/springboot-shoppingmall#65]
안녕하세요 
따로 연락처 안써놓으신거 같아서  이슈로 여쭙는점 죄송합니다.
만들어 놓으신 쇼핑몰 쓰고 싶은데 제 환경에서는 컴파일 에러가 나네요.
STS eclipse, java 1.8.0_291에서 프로젝트 불러오기하면 많은 어노테이션들을 인식못하네요,.
빌드 패스를 재설정해보는 시도를 많이 했는데 에러 2개로까지 줄여도 빌드는 안됩니다..ㅠ
인텔리제이로 해도 메인클래스 찾을 수 없다고 하고 빌드는 안되요 ;ㅁ;

https://drive.google.com/file/d/16TlWFCAjSZw4ItOFJmyX91wYfwGahAxf/view?usp=sharing
https://drive.google.com/file/d/1qQ9JuNcDajrFtedcpovpkC0IPOP0uC6y/view?usp=sharing

혹시 제 컴으로 원격하셔서 환경설정 + 프로젝트 설명 가능하신지 궁금합니다.
물론 페이는 드립니다.

사용하고 싶은데 저의 능력밖이네요. 
제가 삽질하는 건 의미가 없을것 같아서 시간과 노력을 아끼고자 도움 요청드려요.
이쪽으로 연락주시면 감사하겠습니다.
haenemm@naver.com

**Comment by didrlgus** [comment]
안녕하세요. @shin-minkyung 님. 답변이 늦어 죄송합니다.
해당 쇼핑몰 프로젝트는 제가 개인적인 공부를 목적으로 만든 프로젝트입니다.
제가 만든 쇼핑몰을 쓰고 싶다고 하셨는데요. 쓴다는 것이 만약 다른 사람들이 실제로 상용화해서 쓰게 하고 싶다는 목적이시라면, 제가 만든 해당 프로젝트는 개인적인 공부를 목적으로 만든 프로젝트이기 때문에 그건 좀 어려울 것 같습니다.
