### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by prde9306** [didrlgus/springboot-shoppingmall#66]
안녕하세요 덕분에 좋은 자료로 공부 열심히 하고 있는 학생입니다..  감사합니다!!
혹시 관리자 계정을 볼 수 있는 방법은 없을까요?? 배포된 쇼핑몰에 회원가입하여 사용자입장에서는 확인해 봤는데 관리자 계정쪽이 어떻게 되어있는지 궁금해서요...

**Comment by didrlgus** [comment]
안녕하세요. @prde9306 님!
제가 만든 자료가 도움이 되다니 제가 더 영광이네요. ㅎㅎ
사실, 제가 해당 프로젝트에 대한 관리자 계정을 직접 생성하는 기능을 따로 만들지는 않았어요. 
그래서 수동으로 DB에 접근해서 관리자 권한을 줘야 관리자 권한을 얻을 수 있어요.
개인공부를 목적으로 프로젝트를 만든것이다 보니 부족한 점이 많아요.
관리자 계정이라고 해서 많은 기능을 추가해 놓지는 않았지만, 그래도 관리자 권한을 갖는 계정에 대해 궁금하시다면 @prde9306 님 메일을 알려주시겠어요?
관리자 계정을 하나 만들어서 @prde9306 메일로 보내드리겠습니다.

**Comment by prde9306** [comment]
오.. ㅎㅎ 이렇게 좋은 자료 공유해주셔서 정말 감사합니다.   제 메일은 prde9306@gmail.com입니다.

**Comment by didrlgus** [comment]
@prde9306 메일 보내드렸습니다.
저장돼있는 데이터들이 의미있는 데이터들은 아니라서 직접 데이터 추가하셔도 무방할거 같아요.
