### ISSUE TITLE
DB Sharding

### ISSUE THREAD

**Issue by didrlgus** [didrlgus/springboot-shoppingmall#7]
# DB Sharding 방법
## **Modular Sharding**
<img width="379" alt="캡처2" src="https://user-images.githubusercontent.com/40568894/91688283-9e363680-eb9c-11ea-8949-47b51d90eef8.PNG">

* Modular Sharding은 PK를 모듈러 연산한 결과로 DB를 특정하는 방식
* **_장점_** : 레인지샤딩에 비해 데이터가 균일하게 분산됨
  * 데이터가 균일하게 분산 된다는 점은 트래픽을 안정적으로 소화하면서도 DB 리소스를 최대한 활용할 수 있는 방법
* **_단점_** : DB를 추가, 제거하는 과정에서 데이터를 재할당 해야 하는 문제가 발생
* Modular Sharding은 데이터량이 일정 수준에서 유지될 것으로 예상되는 데이터 성격을 가진 곳에 적용할 때 어울리는 방식

## **Consistent Hashing**
* [정의](https://ko.wikipedia.org/wiki/%EC%9D%BC%EA%B4%80%EB%90%9C_%ED%95%B4%EC%8B%B1)
* **_장점_**: key설정 시 단순 modular 연산을 하는 방식에서 DB 추가, 제거 시 발생하는 문제를 보완할 수 있음
  * Consistent Hasing을 사용하면 DB 추가,제거 시 재할당 해야 하는 데이터를 최소화 시킬 수 있음
* **_단점_**: DB를 추가, 제거 하는 과정에서 데이터의 분산이 모든 DB로 균등히 분산되지 않을 수 있음
  * 가상 노드를 적용 시켜 논리적으로 더 많은 노드를 증가 시키는 방식으로 보완 가능 (실제 물리 노드의 개수는 동일)

<img width="391" alt="캡처3" src="https://user-images.githubusercontent.com/40568894/91689540-4b11b300-eb9f-11ea-9849-2d024cdb805d.PNG">
<img width="419" alt="캡처4" src="https://user-images.githubusercontent.com/40568894/91689547-4ea53a00-eb9f-11ea-9d87-c5752cbc79a0.PNG">

## **Range Sharding**
<img width="356" alt="캡처5" src="https://user-images.githubusercontent.com/40568894/91690296-aa23f780-eba0-11ea-8fbc-0a6568af01a1.PNG">

* 레인지샤딩은 PK의 범위를 기준으로 DB를 특정하는 방식
* **_장점_** : Modular Sharding 에 비해 DB 추가, 제거에 용이함
  * 데이터가 급격히 증가할 여지가 있다면 레인지방식도 좋은 선택
* **_단점_** : 일부 DB에 데이터가 몰릴 수 있음

## 참고자료
* [https://woowabros.github.io/experience/2020/07/06/db-sharding.html](https://woowabros.github.io/experience/2020/07/06/db-sharding.html)
* [https://brunch.co.kr/@springboot/258](https://brunch.co.kr/@springboot/258)
* [https://www.toptal.com/big-data/consistent-hashing](https://www.toptal.com/big-data/consistent-hashing)

**Comment by joey-yoonsung** [comment]
장, 단점을 잘 정리해주셨네요. 제가 전에 서비스 만들때도 동일하게 3가지 옵션을 검토했고(사실 3번은 너무 단순한 아이디어여서 당연히 후보가 되지는 못하지만), consistent hashing을 선택했어요. 

질문을 드리자면, 
1. 일반적인 경우(특별한 서비스를 생각하지 않고)에 어떤 방법이 좋을까요?
2. 기현님이 만든 서비스의 트래픽 패턴 (유저 사용패턴) , 그리고 그에따라 특정 테이블을 생각할때는 어떤 방법이 좋을까요? 아래 세가지 테이블을 대상으로 생각해주세요. (웹 서비스에서 가장 많이 쓰이는 대표적인 테이블이기도함)
  * 유저테이블
  * 상품정보 테이블
  * 리뷰 테이블
