### ISSUE TITLE
스프링 서버를 병렬로 하여 성능 테스트

### ISSUE THREAD

**Issue by didrlgus** [didrlgus/springboot-shoppingmall#9]
### 🤖 환경 세팅
<img width="607" alt="캡처" src="https://user-images.githubusercontent.com/40568894/92684566-b6fad500-f370-11ea-94c7-9f1fd462dcae.PNG">

|server|vCPU|mem(GB)|
|-----:|-------:|------:|
|Test Server|2|8|
|Load Balancer Server|1|1|
|App Server1|4|16|
|App Server2|4|16|
|DB Server|8|32|

> nginx 의 load balancer 는 Round Robin 방식
> 각 스프링 서버의 connection pool size는 512
> DB 의 connection size는 1024

### 📝  nginx 설정
> /etc/nginx/nginx.conf
```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    index   index.html index.htm;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  localhost;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
           proxy_pass http://backend;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header Host $http_host;
        }
        
        # redirect server error pages to the static page /40x.html
        #
        error_page 404 /404.html;
            location = /40x.html {
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

    upstream backend {
        server 54.180.139.146:8081;
        server 54.180.151.52:8081;
    }
}
```

### 🤖 **Test1**
|vUser|iter|tps|성공 요청|실패 요청|
|-----:|-------:|------:|------:|------:|
|1000|150000|361|115312|34688|

> 서버를 병렬로 하지 않았을 때보다 오히려 tps가 낮게 나왔으며
> 모든 요청을 다 성공 시키지 못하고 request timeout 으로 인한 실패 요청이 생겼다.

### 🤖 **Test2**
> 위의 설정에서 load balancer 서버의 스펙만 업그레이드
> 나머지 설정 동일

|server|vCPU|mem(GB)|
|-----:|-------:|------:|
|Test Server|2|8|
|Load Balancer Server|4|16|
|App Server1|4|16|
|App Server2|4|16|
|DB Server|8|32|

|vUser|iter|tps|성공 요청|실패 요청|
|-----:|-------:|------:|------:|------:|
|1000|150000|263|149737|263|

> 위의 환경보다 오히려 tps가 낮게 나옴
> 다만, 실패 요청 수 는 줄어듦.

### 📝 nginx 설정 변경
```
...
location / {
   proxy_pass http://backend;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header Host $http_host;
   proxy_connect_timeout 300; 
   proxy_read_timeout 300;
   proxy_send_timeout 300;
   send_timeout 300;
}
...
```

### 🤖 **Test3**
> nginx 의 설정 변경 후 테스트

* sql 로그를 주석 처리 하기 전

|vUser|iter|tps|성공 요청|실패 요청|
|-----:|-------:|------:|------:|------:|
|1000|150000|248|149616|384|

* sql 로그를 주석 처리한 후

|vUser|iter|tps|성공 요청|실패 요청|
|-----:|-------:|------:|------:|------:|
|1000|150000|615|149915|85|
---
> sql 로그를 주석 처리 하면 600대의 tps 를 얻을 수 있지만 여전히 실패 요청 발생
```
2020/09/11 12:59:38 [crit] 3084#0: *102154 open() "/usr/share/nginx/html/50x.html" failed (24: Too many open files), client: 54.180.138.10, server: localhost, request: "GET / HTTP/1.1", upstream: "http://3.35.133.45:8081/", host: "13.209.16.8:80"
2020/09/11 12:59:39 [crit] 3084#0: accept4() failed (24: Too many open files)
```
> nginx 에서 위와 같은 error 가 발생

### 📝 에러 발생 원인
* linux 에서 하나의 connection 은 하나의 fd (file descriptor) 이다. 그리고 이 fd 의 수는 65536 (short type 의 max) 개가 한계.
* nginx 와 스프링 서버 사이에 걸려있는(응답 대기 중인) connection이 많기 때문에 발생하는 문제일 것으로 예상.
* 결과적으로 여기서 에러 응답 없이 더 많은 tps를 받으려면 스프링 서버의 응답 시간(latency) 를 줄여야 할 것이라고 판단됨.

**Comment by joey-yoonsung** [comment]
넵. load balancer 의 코어와 메모리가 낮아서 그럴 것 같습니다. nginx 쪽 로그도 살펴보시면 도움이 될것 같습니다.

**Comment by didrlgus** [comment]
> 넵. load balancer 의 코어와 메모리가 낮아서 그럴 것 같습니다. nginx 쪽 로그도 살펴보시면 도움이 될것 같습니다.

알겠습니다 :)
